#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           lftDrive,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rtDrive,       tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void straightLine()
{
	if(nMotorEncoder[lftDrive] < nMotorEncoder[rtDrive])
	{
		motor[lftDrive] = 64;
		motor[rtDrive] = 0;
	}
	else if(nMotorEncoder[lftDrive] > nMotorEncoder[rtDrive])
	{
		motor[lftDrive] = 0;
		motor[rtDrive] = 64;
	}
	else
	{
		motor[lftDrive] = 127;
		motor[rtDrive] = 127;
	}
}

task main()
{
	while(true)
	{
		straightLine;
	}
}
